### ISSUE TITLE
请问预设场景的参数代表什么

### ISSUE THREAD

**Issue by tangvery** [MissThee/threejs-minecraft#7]
[0, 5, 0, "stone", null, null, null]

**Comment by MissThee** [comment]
这个数组。。。
前三个是方块的位置坐标；
第四个字符串是方块名称，对应src/mc/objects/cube/DefaultCube.ts中的各个对象的键值，表示不同的方块;
最后三个是此方块在相对x,y,z轴的旋转角度，为falsy值时相当于0;
